"""Added admin

Revision ID: 803e917f9563
Revises: 
Create Date: 2026-07-11 17:14:50.068866

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '803e917f9563'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('resume_report', schema=None) as batch_op:
        batch_op.add_column(sa.Column('filepath', sa.String(length=500), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('resume_report', schema=None) as batch_op:
        batch_op.drop_column('filepath')

    # ### end Alembic commands ###
